services:
  proxywi-server:
    container_name: proxywi-server
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    image: proxywi-server:dev
    restart: unless-stopped
    environment:
      PROXYWI_DOMAIN:      "localhost"
      ACME_EMAIL:          "dev@localhost"
      PROXYWI_MAIN_DOMAIN: "localhost"
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"
      - "8080:8080"

  proxywi-client:
    container_name: proxywi-client
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    image: proxywi-client:dev
    restart: unless-stopped
    depends_on:
      - proxywi-server
    environment:
      PROXYWI_SERVER: "ws://proxywi-server:3000"
      PROXYWI_TOKEN:  "4b77d16eb1b21247161dbf7005206b2d9736927adb533cfacf4349b103d04879"
